[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

# Tell pytest how to find your source code in the 'src' directory
addopts = "--pyargs"
pythonpath = ["src"]
